extends:
  template: ../azure-pipelines-template.yml
  parameters:
    dockerfilePath: "$(Build.SourcesDirectory)/contacts-query/Dockerfile"

pr:
  branches:
    include:
      - "*"

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "contacts-command/*"
      - "users/*"
