extends:
  template: ../azure-pipelines-template.yml

pr:
  branches:
    include:
      - "*"

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "contacts-command/*"
      - "users/*"
