extends:
  template: ../azure-pipelines-template.yml
  parameters:
    dockerfilePath: "$(Build.SourcesDirectory)/contacts-query/Dockerfile"
    dockerComposeFilePath: "$(Build.SourcesDirectory)/contacts-query/docker-compose.yml"
    testsProjectPath: "$(Build.SourcesDirectory)/contacts-query/PosTech.TechChallenge.Contacts.Query.Tests/*.csproj"
    unitTestFilter: "--filter FullyQualifiedName~PosTech.TechChallenge.Contacts.Query.Tests.Unit.UseCases"
    integrationTestFilter: "--filter FullyQualifiedName~PosTech.TechChallenge.Contacts.Query.Tests.Integration"
    baseMSPath: "$(Build.SourcesDirectory)/contacts-query/**/*.csproj"

pr:
  branches:
    include:
      - "*"

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "contacts-command/*"
      - "users/*"
