extends:
  template: ../azure-pipelines-template.yml
  parameters:
    dockerfilePath: "$(Build.SourcesDirectory)/users/Dockerfile"
    dockerComposeFilePath: "$(Build.SourcesDirectory)/users/docker-compose.yml"
    testsProjectPath: "$(Build.SourcesDirectory)/users/PosTech.TechChallenge.Users.Tests/*.csproj"
    unitTestFilter: "--filter FullyQualifiedName~PosTech.TechChallenge.Users.Tests.Unit"
    integrationTestFilter: "--filter FullyQualifiedName~PosTech.TechChallenge.Users.Tests.Integration"
    baseMSPath: "$(Build.SourcesDirectory)/users/**/*.csproj"

pr:
  branches:
    include:
      - "*"

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "contacts-query/*"
      - "contacts-command/*"
