extends:
  template: ../azure-pipelines-template.yml
  parameters:
    dockerfilePath: "$(Build.SourcesDirectory)/users/Dockerfile"

pr:
  branches:
    include:
      - "*"

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "contacts-query/*"
      - "contacts-command/*"
