apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://contacts_command_prometheus:9090
    isDefault: true
    uid: PBFA97CFB590B2093
    jsonData:
      timeInterval: 5s
